version: "3.7"
services:
  order-service:
    image: congzhao0294/order-service:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - backend_services
  virtual-customer:
    image: congzhao0294/virtual-customer:latest
    container_name: 'virtual-customer'
    restart: always
    environment:
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
      - ORDERS_PER_HOUR=${ORDERS_PER_HOUR}
    networks:
      - backend_services
    depends_on:
      order-service:
        condition: service_healthy
networks:
  backend_services:
    driver: bridge